spring:
  datasource:
    url: jdbc:mysql://10.1.1.235:3308/tps_order?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: tps138dev
    password: F52o0QJCg8@L
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    proxy-target-class: true
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone:  http://10.1.1.113:8761/eureka/,http://10.1.1.115:8761/eureka/
      fetchRegistry: true
      healthcheck:
        enabled: true


mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.tps.model
  config-location: classpath:mybatis-config.xml