spring:
  datasource:
    url: jdbc:mysql://10.1.1.235:3308/tps_order?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: tps138dev
    password: F52o0QJCg8@L
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    proxy-target-class: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.1.113:8761/eureka/,http://10.1.1.115:8761/eureka/


mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.tps.model
  config-location: classpath:mybatis-config.xml